# Generated by Django 4.2.20 on 2026-04-06 21:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('structure', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hypotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('taux_remboursement', models.FloatField()),
                ('statut_remboursement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('date_leve', models.DateField()),
                ('agent_leve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypobank.agentleve')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('physique', 'Personne Physique'), ('morale', 'Société')], max_length=10)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('raison_sociale', models.CharField(blank=True, max_length=200)),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('domicile', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TitreFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titre', models.CharField(max_length=100)),
                ('verrouillage', models.BooleanField(default=False)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypobank.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypobank.parcelle')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypobank.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('hypotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypobank.hypotheque')),
            ],
        ),
        migrations.AddField(
            model_name='hypotheque',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypobank.titrefoncier'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type_document', models.CharField(max_length=100)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypobank.titrefoncier')),
            ],
        ),
    ]
