# Generated by Django 4.2.20 on 2026-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypobank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypotheque',
            name='taux_remboursement',
        ),
        migrations.AlterField(
            model_name='hypotheque',
            name='statut_remboursement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20),
        ),
    ]
